### ISSUE TITLE
Spreadsheet client not showing it's remote methods in vs code suggestions

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/module-ballerinax-googleapis.sheets#126]
**Description:**
Spreadsheet client only shows these functions in vs code as suggsetions.
<img width="801" alt="Screenshot 2021-01-22 at 22 01 31" src="https://user-images.githubusercontent.com/19742678/105517731-666f8d00-5cfd-11eb-83f6-5ece916be837.png">

I think the reason is there are some remote functions that are not public.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by RolandHewage** [comment]
This issue is already solved
https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets/blob/master/gsheet/client.bal

![Screenshot from 2021-09-17 13-06-37](https://user-images.githubusercontent.com/44081958/133743660-e8e00a83-dfee-4de3-b6cd-05b6973a4d97.png)

Therefore closing this issue.
